name: Create Preview Environment


on:
  pull_request:
    branches:
      - main


concurrency:
  group: preview-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Loft CLI
        uses: loft-sh/setup-loft@v2
        with:
          version: v3.0.0
          url: https://8all2ea.loft.host
          
          access-key: ${{ secrets.LOFT_PREVIEW_ACCESS_KEY }}
          
          

      - name: Deploy Preview Environment
        run: |
          INGRESS_HOST=loft-preview-${{ github.event.pull_request.number }}.my-preview-environments.com

          
          loft create vcluster loft-preview-${{ github.event.pull_request.number }} --project preview-env --recreate

          
          helm repo add argo https://argoproj.github.io/argo-helm
          helm install argocd argo/argo-cd --version 5.16.3 \
                                            --create-namespace \
                                            -n argocd \
                                            --set server.ingress.enabled=true \
                                            --set server.ingress.hosts={$INGRESS_HOST}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          header: release
          message: |
            Preview environment deployed at: http://loft-preview-${{ github.event.pull_request.number }}.my-preview-environments.com

